[package]

name = "negotiator"
version = "0.0.0"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]

[[lib]]

name = "negotiator"
path = "src/lib.rs"

[dependencies.http-parse-priority-header]

git = "https://github.com/reem/rust-http-parse-priority-header.git"

